output_directories:
  transcripts: "./data/transcripts"
  audio: "./data/audio"

text_to_speech:
  elevenlabs:
    default_voices:
      question: "Chris"
      answer: "Jessica"
    model: "eleven_multilingual_v2"
  openai:
    default_voices:
      question: "echo"
      answer: "shimmer"
    model: "tts-1-hd"
  google:
    # REF: https://cloud.google.com/text-to-speech/docs/voices
    default_voices:
      answer:
        voice: "en-US-Journey-D"
        #rate: 1.3
        #pitch: -2
      question:
        voice: "en-US-Journey-F"
        #rate: 1.25
        #pitch: +2
  audio_format: "mp3"
  temp_audio_dir: "data/audio/tmp/"
  ending_message: "Bye Bye!"

content_generator:
  gemini_model: "gemini-1.5-pro-latest"
  max_output_tokens: 8192
  prompt_template: "souzatharsis/podcastfy_multimodal"

content_extractor:
  youtube_url_patterns:
    - "youtube.com"
    - "youtu.be"

website_extractor:
  jina_api_url: "https://r.jina.ai"
  markdown_cleaning:
    remove_patterns:
      - '!\[.*?\]\(.*?\)'
      - '\[([^\]]+)\]\([^\)]+\)'
      - 'https?://\S+|www\.\S+'

youtube_transcriber:
  remove_phrases:
    - "[music]"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

main:
  default_tts_model: "openai"


